# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('facebook_page', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('business_type', models.CharField(choices=[('service', 'Service'), ('trade', 'Trade')], default='trade', max_length=250, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.BusinessSegment', verbose_name='Segment'),
        ),
    ]
